[package]
name = "advent-of-code-2022"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
color-eyre = "0.6.2"
eyre = "0.6.8"
rhai = { version = "1.11.0", features = [] }
